routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return redirect('/dashboard');
});

Route::get('/dashboard', 'DashboardController@index')->name('home');

Route::resource('dashboard/user', 'UserController');


Route::get('/dashboard/email/a/{id}', 'Mail\AttachmentController@show')->name('mail.attachment');
Route::post('/dashboard/email/a', 'Mail\AttachmentController@store')->name('mail.attachment.store');

Route::get('/dashboard/email/m/{id}', 'Mail\MessageController@message')->name('mail.message');
Route::delete('/dashboard/email/m/{id}', 'Mail\MessageController@deleteMessage');
Route::put('/dashboard/email/m/{id}', 'Mail\MessageController@actionMessage');

Route::get('/dashboard/email/compose/{id?}', 'Mail\MessageController@compose')->name('mail.compose');
Route::post('/dashboard/email/draft', 'Mail\MessageController@draft')->name('mail.draft');
Route::post('/dashboard/email/send', 'Mail\MessageController@send')->name('mail.send');
Route::get('/dashboard/email/f/{folder}', 'Mail\MessageController@index')->name('mail.index');
Route::delete('/dashboard/email/f/{folder}', 'Mail\MessageController@delete');
Route::put('/dashboard/email/f/{folder}', 'Mail\MessageController@action');

// Schedule

Route::get('/dashboard/schedule', 'Schedule\ScheduleController@index')->name('schedule.index');
Route::post('/dashboard/schedule', 'Schedule\ScheduleController@loadAjax');
Route::get('/dashboard/schedule/my', 'Schedule\ScheduleController@mySchedule')->name('schedule.myschedule');
Route::post('/dashboard/schedule/my', 'Schedule\ScheduleController@loadAjaxMySchedule');
Route::get('/dashboard/schedule/lesson', 'Schedule\LessonController@index')->name('schedule.lesson.index');
Route::get('/dashboard/schedule/lesson/create', 'Schedule\LessonController@create')->name('schedule.lesson.create');
Route::post('/dashboard/schedule/lesson/create', 'Schedule\LessonController@store');
Route::get('/dashboard/schedule/lesson/{id}/edit', 'Schedule\LessonController@edit')->name('schedule.lesson.edit');
Route::put('/dashboard/schedule/lesson/{id}/edit', 'Schedule\LessonController@update');
Route::delete('/dashboard/schedule/lesson/{id}', 'Schedule\LessonController@destroy')->name('schedule.lesson.destroy');


Route::get('/dashboard/calendar', 'CalendarController@index')->name('calendar');
Route::post('/dashboard/calendar', 'CalendarController@events');
Route::get('/dashboard/calendar/create', 'CalendarController@create')->name('calendar.create');
Route::post('/dashboard/calendar/create', 'CalendarController@store');

Route::get('/dashboard/calendar/editmode', 'CalendarController@toggleEditMode')->name('calendar.edit_mode');

Route::get('/dashboard/calendar/edit', 'CalendarController@edit')->name('calendar.edit');
Route::put('/dashboard/calendar/{id}', 'CalendarController@update')->name('calendar.update');
Route::post('/dashboard/calendar/{id}', 'CalendarController@show')->name('calendar.show');
Route::delete('/dashboard/calendar/{id}', 'CalendarController@destroy')->name('calendar.destroy');

// Remote learning

Route::get('/dashboard/remotelearning', 'RemoteLearning\RemoteLearningController@index')->name('remotelearning.index');
Route::post('/dashboard/remotelearning', 'RemoteLearning\RemoteLearningController@controller');
Route::post('/dashboard/remotelearning/records', 'RemoteLearning\RemoteLearningController@records');
Route::post('/dashboard/remotelearning/records/modal', 'RemoteLearning\RemoteLearningController@recordModal')->name('remotelearning.record');
Route::post('/dashboard/remotelearning/checkifstarted', 'RemoteLearning\RemoteLearningController@checkIfStreamStarted')->name('remotelearning.status');

// License

Route::get('/dashboard/license', 'License\LicenseController@index')->name('license.index');
Route::get('/dashboard/license/create', 'License\LicenseController@create')->name('license.create');
Route::post('/dashboard/license/create', 'License\LicenseController@store');
Route::get('/dashboard/license/{id}/edit', 'License\LicenseController@edit')->name('license.edit');
Route::put('/dashboard/license/{id}/edit', 'License\LicenseController@update');
Route::delete('/dashboard/license/{id}', 'License\LicenseController@destroy')->name('license.destroy');
Route::post('/dashboard/license/{id}/extend', 'License\LicenseController@extend')->name('license.extend');

//// License Type

Route::get('/dashboard/license/type', 'License\LicenseTypeController@index')->name('license.type.index');
Route::get('/dashboard/license/type/create', 'License\LicenseTypeController@create')->name('license.type.create');
Route::post('/dashboard/license/type/create', 'License\LicenseTypeController@store');
Route::get('/dashboard/license/type/{id}/edit', 'License\LicenseTypeController@edit')->name('license.type.edit');
Route::put('/dashboard/license/type/{id}/edit', 'License\LicenseTypeController@update');
Route::delete('/dashboard/license/type/{id}', 'License\LicenseTypeController@destroy')->name('license.type.destroy');

//// Legal info

Route::get('/dashboard/license/legalinfo', 'License\LegalInfoController@index')->name('license.legalinfo.index');
Route::get('/dashboard/license/legalinfo/create', 'License\LegalInfoController@create')->name('license.legalinfo.create');
Route::post('/dashboard/license/legalinfo/create', 'License\LegalInfoController@store');
Route::get('/dashboard/license/legalinfo/{id}/edit', 'License\LegalInfoController@edit')->name('license.legalinfo.edit');
Route::put('/dashboard/license/legalinfo/{id}/edit', 'License\LegalInfoController@update');
Route::delete('/dashboard/license/legalinfo/{id}', 'License\LegalInfoController@destroy')->name('license.legalinfo.destroy');
Route::post('/dashboard/license/{id}/toggle', 'License\LegalInfoController@toggle')->name('license.legalinfo.toggle');

// Projects

Route::get('/dashboard/project', 'Project\ProjectController@index')->name('project.index');
Route::get('/dashboard/project/create', 'Project\ProjectController@create')->name('project.create');
Route::post('/dashboard/project/create', 'Project\ProjectController@store');
Route::get('/dashboard/project/{id}/edit', 'Project\ProjectController@edit')->name('project.edit');
Route::put('/dashboard/project/{id}/edit', 'Project\ProjectController@update');
Route::delete('/dashboard/project/{id}', 'Project\ProjectController@destroy')->name('project.destroy');

//// Project Platform

Route::get('/dashboard/project/platform', 'Project\ProjectPlatformController@index')->name('project.platform.index');
Route::get('/dashboard/project/platform/create', 'Project\ProjectPlatformController@create')->name('project.platform.create');
Route::post('/dashboard/project/platform/create', 'Project\ProjectPlatformController@store');
Route::get('/dashboard/project/platform/{id}/edit', 'Project\ProjectPlatformController@edit')->name('project.platform.edit');
Route::put('/dashboard/project/platform/{id}/edit', 'Project\ProjectPlatformController@update');
Route::delete('/dashboard/project/platform/{id}', 'Project\ProjectPlatformController@destroy')->name('project.platform.destroy');

//// Project Tag

Route::get('/dashboard/project/tag', 'Project\ProjectTagController@index')->name('project.tag.index');
Route::get('/dashboard/project/tag/create', 'Project\ProjectTagController@create')->name('project.tag.create');
Route::post('/dashboard/project/tag/create', 'Project\ProjectTagController@store');
Route::get('/dashboard/project/tag/{id}/edit', 'Project\ProjectTagController@edit')->name('project.tag.edit');
Route::put('/dashboard/project/tag/{id}/edit', 'Project\ProjectTagController@update');
Route::get('/dashboard/project/tag/{id}', 'Project\ProjectTagController@show')->name('project.tag.show');
Route::post('/dashboard/project/tag/{id}', 'Project\ProjectTagController@participationRequest');
Route::delete('/dashboard/project/tag/{id}', 'Project\ProjectTagController@destroy')->name('project.tag.destroy');

// Email

Route::get('/dashboard/settings/email', 'Mail\SettingController@settings')->name('settings.mail');
Route::post('/dashboard/settings/email/add_domain', 'Mail\SettingController@addDomain')->name('settings.mail.add_domain');
Route::delete('/dashboard/settings/email/del_domain/{id}', 'Mail\SettingController@delDomain')->name('settings.mail.del_domain');

Route::get('/dashboard/settings/class', 'Settings\ClassController@index')->name('settings.class.index');
Route::get('/dashboard/settings/class/create', 'Settings\ClassController@create')->name('settings.class.create');
Route::post('/dashboard/settings/class/create', 'Settings\ClassController@store');
Route::get('/dashboard/settings/class/{id}/edit', 'Settings\ClassController@edit')->name('settings.class.edit');
Route::put('/dashboard/settings/class/{id}/edit', 'Settings\ClassController@update');
Route::delete('/dashboard/settings/class/{id}', 'Settings\ClassController@destroy')->name('settings.class.destroy');


Route::get('/dashboard/settings/classroom', 'Settings\ClassroomController@index')->name('settings.classroom.index');
Route::get('/dashboard/settings/classroom/create', 'Settings\ClassroomController@create')->name('settings.classroom.create');
Route::post('/dashboard/settings/classroom/create', 'Settings\ClassroomController@store');
Route::get('/dashboard/settings/classroom/{id}/edit', 'Settings\ClassroomController@edit')->name('settings.classroom.edit');
Route::put('/dashboard/settings/classroom/{id}/edit', 'Settings\ClassroomController@update');
Route::delete('/dashboard/settings/classroom/{id}', 'Settings\ClassroomController@destroy')->name('settings.classroom.destroy');


Route::get('/dashboard/settings/subject', 'Settings\SubjectController@index')->name('settings.subject.index');
Route::get('/dashboard/settings/subject/create', 'Settings\SubjectController@create')->name('settings.subject.create');
Route::post('/dashboard/settings/subject/create', 'Settings\SubjectController@store');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Junges\ACL\Traits\UsersTrait;

class User extends Authenticatable
{
    use Notifiable, UsersTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'icon',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'last_activity' => 'datetime'
    ];

    protected $appends = ['icon_url', 'correct_email'];

    protected $with = ['institution'];

    public function getIconUrlAttribute($value = null)
    {
        if(empty($this->icon)) {
            return '/images/no-icon.svg';
        }

        return '/storage/' . $this->icon;
    }

    public function getCorrectEmailAttribute($value = null)
    {
        $mail = $this->mails()->first();

        if(!empty($mail) && $mail->active) {
            return $mail->username.'@'.$mail->domain->domain;
        }

        return $this->email;
    }

    public function getIsOnlineAttribute()
    {
        $session = $this->sessions()->orderBy('last_activity')->first();

        if($session) {
            return $session->last_activity > Carbon::now()->subMinutes(5);
        } else {
            return false;
        }
    }

    public function getValidSessionsAttribute()
    {
        $sessions = $this->sessions()->where('last_activity', '>', Carbon::now()->subMinutes(config('session.lifetime')))->count();

        return $sessions;
    }

    public function enabledEmail()
    {
        $mails = $this->mails()->where('active', 1)->count();

        return $mails > 0;
    }

    public function availableRecordings()
    {
        $class = $this->classes()->first();

        if(empty($class)) return 0;

        $recordings = Lesson::with('recording')->whereHas('recording', function ($query) {
            $query->where('status', 'finished');
        })->where('study_class_id', $class->id)->orderBy('start', 'desc')->count();

        return $recordings;
    }

    public function institution()
    {
        return $this->belongsTo('App\Institution');
    }

    public function mails()
    {
        return $this->hasMany('App\Mail');
    }

    public function classes()
    {
        return $this->belongsToMany('App\StudyClass');
    }

    public function hasClass($class)
    {
        $where = null;

        if (is_numeric($class)) {
            $where = ['id', $class];
        } elseif (is_string($class)) {
            $where = ['name', $class];
        }

        if ($class != null && $where != null) {
            return null !== $this->classes->where(...$where)->first();
        }

        return false;
    }

    public function achivements()
    {
        return $this->belongsToMany('App\Achivement')->withPivot('received');
    }

    public function hasAchivement($achivement)
    {
        $where = null;

        if (is_numeric($achivement)) {
            $where = ['id', $achivement];
        } elseif (is_string($achivement)) {
            $where = ['name', $achivement];
        }

        if ($achivement != null && $where != null) {
            return null !== $this->achivements->where(...$where)->first();
        }

        return false;
    }

    public function subjects()
    {
        return $this->belongsToMany('App\Subject');
    }

    public function hasSubject($subject)
    {
        $where = null;

        if (is_numeric($subject)) {
            $where = ['id', $subject];
        } elseif (is_string($subject)) {
            $where = ['name', $subject];
        }

        if ($subject != null && $where != null) {
            return null !== $this->subjects->where(...$where)->first();
        }

        return false;
    }

    public function datas()
    {
        return $this->hasMany('App\UserData');
    }

    public function hasFavorited($id) 
    {
        return !empty($this->favorites()->where('id', $id)->first());
    }

    public function favorites()
    {
        return $this->belongsToMany('App\User', 'favorites', 'user_id', 'favorited_id');
    }

    public function sessions()
    {
        return $this->hasMany('App\Session');
    }

    public function getData($type, $onlyValue = false)
    {
        $data = $this->datas()->where('type', $type)->first();

        if($data) {
            $data->value = unserialize($data->value);
            if($onlyValue) {
                return $data->value;
            }
        }

        return $data;
    }

    public function setData($data)
    {
        if(!is_array($data)) return false;

        foreach($data as $type => $value) {
            $data = UserData::updateOrCreate([
                'user_id' => $this->id,
                'type' => $type
            ], [
                'value' => $value ? serialize($value) : serialize(null)
            ]);
        }

        return true;
    }
}

resources/views/dashboard/infoblock.blade.php
@extends('layouts.default')

@section('title', __('Инфоблок'))

@push('css')
	<link href="/assets/plugins/jvectormap-next/jquery-jvectormap.css" rel="stylesheet" />
	<link href="/assets/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.css" rel="stylesheet" />
	<link href="/assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" />

	<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
	<link href="/assets/plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')
	<!-- begin breadcrumb -->
	<ol class="breadcrumb float-xl-right">
		<li class="breadcrumb-item">{{ __('Личный кабинет') }}</li>
		<li class="breadcrumb-item active">{{ __('Инфоблок') }}</li>
	</ol>
	<!-- end breadcrumb -->
	<!-- begin page-header -->
	<h1 class="page-header">{{ __('Инфоблок') }} <small>{{ __('все самое главное здесь') }}</small></h1>
	<!-- end page-header -->
	
	<!-- begin row -->
	@group('teacher')
		@include('dashboard.infoblock.teacher_widgets')
	@elsegroup('student')
		@include('dashboard.infoblock.student_widgets')
	@endgroup
	<!-- end row -->
	<!-- begin row -->
	<div class="row">
		<!-- begin col-12 -->
		<div class="col-xl-12">
			@group('teacher')
				@include('dashboard.infoblock.teacher_achivements')
			@elsegroup('student')
				@include('dashboard.infoblock.student_achivements')
			@endgroup

			<!-- begin panel -->
			<div class="panel panel-inverse" data-sortable-id="index-2">
				<div class="panel-heading">
					<h4 class="panel-title">Избранные контакты</h4>
					<div class="panel-heading-btn">
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
					</div>
				</div>
				<div class="panel-body">
					<table id="data-table-contacts" class="table table-striped table-bordered table-td-valign-middle">
						<thead>
							<tr>
								<th width="1%">№</th>
								<th width="1%" data-orderable="false"></th>
								<th class="text-nowrap">Ф.И.О.</th>
								<th class="text-nowrap">Почта</th>
								<th class="text-nowrap">Образовательное учреждение</th>
								<th class="text-nowrap">Статус</th>
								<th class="text-nowrap">Должность</th>
							</tr>
						</thead>
						<tbody>
							@foreach($contacts as $key => $contact)
							<tr>
								<td width="1%" class="f-s-600 text-inverse">{{ $key + 1 }}</td>
								<td width="1%" class="with-img">
									<img src="{{ $contact->icon_url }}" class="img-rounded height-30" />
								</td>
								<td>{{ $contact->name }}</td>
								<td>
									<div class="contact-email">
										<span>{{ $contact->correct_email }}</span>
										@if($contact->enabledEmail())
										@can('use', App\Mail::class)
										<a href="{{ route('mail.compose', ['email' => $contact->correct_email]) }}" class="btn btn-sm btn-primary m-l-20">НАПИСАТЬ</a>
										@endcan
										@endif
									</div>
								</td>
								<td>{{ $contact->institution ? $contact->institution->full_name : '- - -' }}</td>
								<td class="{{ $contact->is_online ? 'online' : 'offline' }}">
									<span>{{ $contact->is_online ? 'В сети' : 'Не в сети' }}</span>
								</td>
								<td>
									@if($contact->hasGroup('principal'))
									<div>{{ __('Директор') }}</div>
									@endif
									@if($contact->hasGroup('support'))
									<div>{{ __('Техподдержка') }}</div>
									@endif
									@if($contact->hasGroup('teacher'))
									<div>{{ __('Преподаватель') }} 
									{{ $contact->subjects ? $contact->subjects->pluck('name')->join(', ') : '' }}
									@endif
									@if($contact->hasGroup('student'))</div>
									<div>{{ __('Ученик') }}</div>
									@endif
									@if($contact->hasGroup('admin'))
									<div>{{ __('Администратор') }}</div>
									@endif 
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
			<!-- end panel -->
		</div>
		<!-- end col-12 -->
	</div>
	<!-- end row -->
@endsection

@push('scripts')
	<script src="/assets/plugins/gritter/js/jquery.gritter.js"></script>
	<script src="/assets/plugins/flot/jquery.flot.js"></script>
	<script src="/assets/plugins/flot/jquery.flot.time.js"></script>
	<script src="/assets/plugins/flot/jquery.flot.resize.js"></script>
	<script src="/assets/plugins/flot/jquery.flot.pie.js"></script>
	<script src="/assets/plugins/jquery-sparkline/jquery.sparkline.min.js"></script>
	<script src="/assets/plugins/jvectormap-next/jquery-jvectormap.min.js"></script>
	<script src="/assets/plugins/jvectormap-next/jquery-jvectormap-world-mill.js"></script>
	<script src="/assets/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
	<!-- <script src="/assets/js/demo/dashboard.js?v=2"></script> -->

	<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
	<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
	<script src="/assets/plugins/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
	<script src="/assets/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
	<script src="/assets/plugins/datatables.net-autofill/js/dataTables.autofill.min.js"></script>
	<script src="/assets/plugins/datatables.net-autofill-bs4/js/autofill.bootstrap4.min.js"></script>

@endpush