routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return redirect('/dashboard');
});

Route::get('/dashboard', 'DashboardController@index')->name('home');

Route::resource('dashboard/user', 'UserController');


Route::get('/dashboard/email/a/{id}', 'Mail\AttachmentController@show')->name('mail.attachment');
Route::post('/dashboard/email/a', 'Mail\AttachmentController@store')->name('mail.attachment.store');

Route::get('/dashboard/email/m/{id}', 'Mail\MessageController@message')->name('mail.message');
Route::delete('/dashboard/email/m/{id}', 'Mail\MessageController@deleteMessage');
Route::put('/dashboard/email/m/{id}', 'Mail\MessageController@actionMessage');

Route::get('/dashboard/email/compose/{id?}', 'Mail\MessageController@compose')->name('mail.compose');
Route::post('/dashboard/email/draft', 'Mail\MessageController@draft')->name('mail.draft');
Route::post('/dashboard/email/send', 'Mail\MessageController@send')->name('mail.send');
Route::get('/dashboard/email/f/{folder}', 'Mail\MessageController@index')->name('mail.index');
Route::delete('/dashboard/email/f/{folder}', 'Mail\MessageController@delete');
Route::put('/dashboard/email/f/{folder}', 'Mail\MessageController@action');

// Schedule

Route::get('/dashboard/schedule', 'Schedule\ScheduleController@index')->name('schedule.index');
Route::post('/dashboard/schedule', 'Schedule\ScheduleController@loadAjax');
Route::get('/dashboard/schedule/my', 'Schedule\ScheduleController@mySchedule')->name('schedule.myschedule');
Route::post('/dashboard/schedule/my', 'Schedule\ScheduleController@loadAjaxMySchedule');
Route::get('/dashboard/schedule/lesson', 'Schedule\LessonController@index')->name('schedule.lesson.index');
Route::get('/dashboard/schedule/lesson/create', 'Schedule\LessonController@create')->name('schedule.lesson.create');
Route::post('/dashboard/schedule/lesson/create', 'Schedule\LessonController@store');
Route::get('/dashboard/schedule/lesson/{id}/edit', 'Schedule\LessonController@edit')->name('schedule.lesson.edit');
Route::put('/dashboard/schedule/lesson/{id}/edit', 'Schedule\LessonController@update');
Route::delete('/dashboard/schedule/lesson/{id}', 'Schedule\LessonController@destroy')->name('schedule.lesson.destroy');


Route::get('/dashboard/calendar', 'CalendarController@index')->name('calendar');
Route::post('/dashboard/calendar', 'CalendarController@events');
Route::get('/dashboard/calendar/create', 'CalendarController@create')->name('calendar.create');
Route::post('/dashboard/calendar/create', 'CalendarController@store');

Route::get('/dashboard/calendar/editmode', 'CalendarController@toggleEditMode')->name('calendar.edit_mode');

Route::get('/dashboard/calendar/edit', 'CalendarController@edit')->name('calendar.edit');
Route::put('/dashboard/calendar/{id}', 'CalendarController@update')->name('calendar.update');
Route::post('/dashboard/calendar/{id}', 'CalendarController@show')->name('calendar.show');
Route::delete('/dashboard/calendar/{id}', 'CalendarController@destroy')->name('calendar.destroy');

// Remote learning

Route::get('/dashboard/remotelearning', 'RemoteLearning\RemoteLearningController@index')->name('remotelearning.index');
Route::post('/dashboard/remotelearning', 'RemoteLearning\RemoteLearningController@controller');
Route::post('/dashboard/remotelearning/records', 'RemoteLearning\RemoteLearningController@records');
Route::post('/dashboard/remotelearning/records/modal', 'RemoteLearning\RemoteLearningController@recordModal')->name('remotelearning.record');
Route::post('/dashboard/remotelearning/checkifstarted', 'RemoteLearning\RemoteLearningController@checkIfStreamStarted')->name('remotelearning.status');

// License

Route::get('/dashboard/license', 'License\LicenseController@index')->name('license.index');
Route::get('/dashboard/license/create', 'License\LicenseController@create')->name('license.create');
Route::post('/dashboard/license/create', 'License\LicenseController@store');
Route::get('/dashboard/license/{id}/edit', 'License\LicenseController@edit')->name('license.edit');
Route::put('/dashboard/license/{id}/edit', 'License\LicenseController@update');
Route::delete('/dashboard/license/{id}', 'License\LicenseController@destroy')->name('license.destroy');
Route::post('/dashboard/license/{id}/extend', 'License\LicenseController@extend')->name('license.extend');

//// License Type

Route::get('/dashboard/license/type', 'License\LicenseTypeController@index')->name('license.type.index');
Route::get('/dashboard/license/type/create', 'License\LicenseTypeController@create')->name('license.type.create');
Route::post('/dashboard/license/type/create', 'License\LicenseTypeController@store');
Route::get('/dashboard/license/type/{id}/edit', 'License\LicenseTypeController@edit')->name('license.type.edit');
Route::put('/dashboard/license/type/{id}/edit', 'License\LicenseTypeController@update');
Route::delete('/dashboard/license/type/{id}', 'License\LicenseTypeController@destroy')->name('license.type.destroy');

//// Legal info

Route::get('/dashboard/license/legalinfo', 'License\LegalInfoController@index')->name('license.legalinfo.index');
Route::get('/dashboard/license/legalinfo/create', 'License\LegalInfoController@create')->name('license.legalinfo.create');
Route::post('/dashboard/license/legalinfo/create', 'License\LegalInfoController@store');
Route::get('/dashboard/license/legalinfo/{id}/edit', 'License\LegalInfoController@edit')->name('license.legalinfo.edit');
Route::put('/dashboard/license/legalinfo/{id}/edit', 'License\LegalInfoController@update');
Route::delete('/dashboard/license/legalinfo/{id}', 'License\LegalInfoController@destroy')->name('license.legalinfo.destroy');
Route::post('/dashboard/license/{id}/toggle', 'License\LegalInfoController@toggle')->name('license.legalinfo.toggle');

// Projects

Route::get('/dashboard/project', 'Project\ProjectController@index')->name('project.index');
Route::get('/dashboard/project/create', 'Project\ProjectController@create')->name('project.create');
Route::post('/dashboard/project/create', 'Project\ProjectController@store');
Route::get('/dashboard/project/{id}/edit', 'Project\ProjectController@edit')->name('project.edit');
Route::put('/dashboard/project/{id}/edit', 'Project\ProjectController@update');
Route::delete('/dashboard/project/{id}', 'Project\ProjectController@destroy')->name('project.destroy');

//// Project Platform

Route::get('/dashboard/project/platform', 'Project\ProjectPlatformController@index')->name('project.platform.index');
Route::get('/dashboard/project/platform/create', 'Project\ProjectPlatformController@create')->name('project.platform.create');
Route::post('/dashboard/project/platform/create', 'Project\ProjectPlatformController@store');
Route::get('/dashboard/project/platform/{id}/edit', 'Project\ProjectPlatformController@edit')->name('project.platform.edit');
Route::put('/dashboard/project/platform/{id}/edit', 'Project\ProjectPlatformController@update');
Route::delete('/dashboard/project/platform/{id}', 'Project\ProjectPlatformController@destroy')->name('project.platform.destroy');

//// Project Tag

Route::get('/dashboard/project/tag', 'Project\ProjectTagController@index')->name('project.tag.index');
Route::get('/dashboard/project/tag/create', 'Project\ProjectTagController@create')->name('project.tag.create');
Route::post('/dashboard/project/tag/create', 'Project\ProjectTagController@store');
Route::get('/dashboard/project/tag/{id}/edit', 'Project\ProjectTagController@edit')->name('project.tag.edit');
Route::put('/dashboard/project/tag/{id}/edit', 'Project\ProjectTagController@update');
Route::get('/dashboard/project/tag/{id}', 'Project\ProjectTagController@show')->name('project.tag.show');
Route::post('/dashboard/project/tag/{id}', 'Project\ProjectTagController@participationRequest');
Route::delete('/dashboard/project/tag/{id}', 'Project\ProjectTagController@destroy')->name('project.tag.destroy');

// Email

Route::get('/dashboard/settings/email', 'Mail\SettingController@settings')->name('settings.mail');
Route::post('/dashboard/settings/email/add_domain', 'Mail\SettingController@addDomain')->name('settings.mail.add_domain');
Route::delete('/dashboard/settings/email/del_domain/{id}', 'Mail\SettingController@delDomain')->name('settings.mail.del_domain');

Route::get('/dashboard/settings/class', 'Settings\ClassController@index')->name('settings.class.index');
Route::get('/dashboard/settings/class/create', 'Settings\ClassController@create')->name('settings.class.create');
Route::post('/dashboard/settings/class/create', 'Settings\ClassController@store');
Route::get('/dashboard/settings/class/{id}/edit', 'Settings\ClassController@edit')->name('settings.class.edit');
Route::put('/dashboard/settings/class/{id}/edit', 'Settings\ClassController@update');
Route::delete('/dashboard/settings/class/{id}', 'Settings\ClassController@destroy')->name('settings.class.destroy');


Route::get('/dashboard/settings/classroom', 'Settings\ClassroomController@index')->name('settings.classroom.index');
Route::get('/dashboard/settings/classroom/create', 'Settings\ClassroomController@create')->name('settings.classroom.create');
Route::post('/dashboard/settings/classroom/create', 'Settings\ClassroomController@store');
Route::get('/dashboard/settings/classroom/{id}/edit', 'Settings\ClassroomController@edit')->name('settings.classroom.edit');
Route::put('/dashboard/settings/classroom/{id}/edit', 'Settings\ClassroomController@update');
Route::delete('/dashboard/settings/classroom/{id}', 'Settings\ClassroomController@destroy')->name('settings.classroom.destroy');


Route::get('/dashboard/settings/subject', 'Settings\SubjectController@index')->name('settings.subject.index');
Route::get('/dashboard/settings/subject/create', 'Settings\SubjectController@create')->name('settings.subject.create');
Route::post('/dashboard/settings/subject/create', 'Settings\SubjectController@store');

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Junges\ACL\Traits\UsersTrait;

class User extends Authenticatable
{
    use Notifiable, UsersTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'icon',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'last_activity' => 'datetime'
    ];

    protected $appends = ['icon_url', 'correct_email'];

    protected $with = ['institution'];

    public function getIconUrlAttribute($value = null)
    {
        if(empty($this->icon)) {
            return '/images/no-icon.svg';
        }

        return '/storage/' . $this->icon;
    }

    public function getCorrectEmailAttribute($value = null)
    {
        $mail = $this->mails()->first();

        if(!empty($mail) && $mail->active) {
            return $mail->username.'@'.$mail->domain->domain;
        }

        return $this->email;
    }

    public function getIsOnlineAttribute()
    {
        $session = $this->sessions()->orderBy('last_activity')->first();

        if($session) {
            return $session->last_activity > Carbon::now()->subMinutes(5);
        } else {
            return false;
        }
    }

    public function getValidSessionsAttribute()
    {
        $sessions = $this->sessions()->where('last_activity', '>', Carbon::now()->subMinutes(config('session.lifetime')))->count();

        return $sessions;
    }

    public function enabledEmail()
    {
        $mails = $this->mails()->where('active', 1)->count();

        return $mails > 0;
    }

    public function availableRecordings()
    {
        $class = $this->classes()->first();

        if(empty($class)) return 0;

        $recordings = Lesson::with('recording')->whereHas('recording', function ($query) {
            $query->where('status', 'finished');
        })->where('study_class_id', $class->id)->orderBy('start', 'desc')->count();

        return $recordings;
    }

    public function institution()
    {
        return $this->belongsTo('App\Institution');
    }

    public function mails()
    {
        return $this->hasMany('App\Mail');
    }

    public function classes()
    {
        return $this->belongsToMany('App\StudyClass');
    }

    public function hasClass($class)
    {
        $where = null;

        if (is_numeric($class)) {
            $where = ['id', $class];
        } elseif (is_string($class)) {
            $where = ['name', $class];
        }

        if ($class != null && $where != null) {
            return null !== $this->classes->where(...$where)->first();
        }

        return false;
    }

    public function achivements()
    {
        return $this->belongsToMany('App\Achivement')->withPivot('received');
    }

    public function hasAchivement($achivement)
    {
        $where = null;

        if (is_numeric($achivement)) {
            $where = ['id', $achivement];
        } elseif (is_string($achivement)) {
            $where = ['name', $achivement];
        }

        if ($achivement != null && $where != null) {
            return null !== $this->achivements->where(...$where)->first();
        }

        return false;
    }

    public function subjects()
    {
        return $this->belongsToMany('App\Subject');
    }

    public function hasSubject($subject)
    {
        $where = null;

        if (is_numeric($subject)) {
            $where = ['id', $subject];
        } elseif (is_string($subject)) {
            $where = ['name', $subject];
        }

        if ($subject != null && $where != null) {
            return null !== $this->subjects->where(...$where)->first();
        }

        return false;
    }

    public function datas()
    {
        return $this->hasMany('App\UserData');
    }

    public function hasFavorited($id) 
    {
        return !empty($this->favorites()->where('id', $id)->first());
    }

    public function favorites()
    {
        return $this->belongsToMany('App\User', 'favorites', 'user_id', 'favorited_id');
    }

    public function sessions()
    {
        return $this->hasMany('App\Session');
    }

    public function getData($type, $onlyValue = false)
    {
        $data = $this->datas()->where('type', $type)->first();

        if($data) {
            $data->value = unserialize($data->value);
            if($onlyValue) {
                return $data->value;
            }
        }

        return $data;
    }

    public function setData($data)
    {
        if(!is_array($data)) return false;

        foreach($data as $type => $value) {
            $data = UserData::updateOrCreate([
                'user_id' => $this->id,
                'type' => $type
            ], [
                'value' => $value ? serialize($value) : serialize(null)
            ]);
        }

        return true;
    }
}

resources/views/dashboard/users/edit/achivements.blade.php
<div class="tab-pane fade @if($settings_tab == 'achivements-settings') active show @endif" id="achivements-settings">
	<form action="{{ route('user.update', $user->id) }}" method="POST">
		@csrf
		{{ method_field('PATCH') }}
		<input type="hidden" name="tab" value="achivements-settings">
		
		@foreach($achivement_groups as $group)
		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ $group->name }}</label>
			<div class="col-md-9">
				<select multiple="" name="achivements[]" class="form-control selectpicker" data-size="10" data-live-search="true">
					@foreach($group->achivements as $achivement)
						<option value="{{ $achivement->id }}" {{ ($user->hasAchivement($achivement->id)) ? 'selected':'' }}>{{ $achivement->name }}</option>
					@endforeach
				</select>
			</div>
		</div>
		@endforeach

		
		<div class="form-group row">
			<div class="col-md-7 offset-md-3">
				<button type="submit" class="btn btn-lg btn-primary m-r-5">{{ __('Сохранить') }}</button>
			</div>
		</div>
	</form>
</div>

@push('scripts')
	<script src="/assets/js/users/edit/achivements.min.js?ver={{ config('app.version') }}"></script>
@endpush

resources/views/dashboard/users/edit/default.blade.php
<div class="tab-pane fade @if($settings_tab == 'default-settings') active show @endif" id="default-settings">
	<form action="{{ route('user.update', $user->id) }}" enctype="multipart/form-data" method="POST">
		@csrf
		{{ method_field('PATCH') }}
		<input type="hidden" name="tab" value="default-settings">
		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Имя') }}</label>
			<div class="col-md-9">
				<input type="text" name="name" class="form-control m-b-5 @error('name', 'default') is-invalid @enderror" value="{{ $user->name }}" placeholder="{{ __('Введите имя...') }}" >
				@error('name', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>

		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Количество одновременных сессий') }}</label>
			<div class="col-md-9">
				<input type="text" name="session_limit" class="form-control m-b-5 @error('session_limit', 'default') is-invalid @enderror" value="{{ $user->getData('session_limit', true) }}" placeholder="{{ __('Введите количество...') }}" >
				@error('session_limit', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>

		<div class="form-group row m-b-15">
		    <label class="col-form-label col-md-3">{{ __('Иконка') }}</label>
		    <div class="col-md-9">
		    	@if($user->icon)
		    	<div class="form-check m-b-10">
					<img src="{{$user->icon_url}}" width="100px" height="auto">
				</div>
			    <div class="form-check m-b-10">
					<input type="checkbox" name="del_icon" value="1" id="delete-icon" class="form-check-input">
					<label class="form-check-label" for="delete-icon">{{ __('Удалить иконку') }}</label>
				</div>
				@endif
		    	<input type="file" name="icon" class="form-control-file @error('icon', 'default') is-invalid @enderror">
		    	@error('icon', 'default')
	                <span class="invalid-feedback" role="alert">
	                    <strong>{{ $message }}</strong>
	                </span>
	            @enderror
		    </div>
		</div>
		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Email') }}</label>
			<div class="col-md-9">
				<input type="email" name="email" class="form-control m-b-5 @error('email', 'default') is-invalid @enderror" value="{{ $user->email }}" placeholder="{{ __('Введите Email...') }}" >
				@error('email', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>
		@if(Auth::user()->id != $user->id)
		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Группы') }}</label>
			<div class="col-md-9">
				<select multiple="" name="groups[]" class="form-control @error('groups', 'default') is-invalid @enderror">
					@foreach($groups as $group)
						<option value="{{ $group->slug }}" {{ ($user->hasGroup($group->id)) ? 'selected':'' }}>{{ $group->name }}</option>
					@endforeach
				</select>
				@error('groups', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>
		@endif

		<div class="form-group row m-b-15" id="institution-block">
			<label class="col-form-label col-md-3">{{ __('Учебное учреждение') }}</label>
			<div class="col-md-9">
				<select name="institution" class="form-control @error('institution', 'default') is-invalid @enderror selectpicker" multiple data-max-options="1" data-live-search="true">
					@foreach($institutions as $institution)
						<option value="{{ $institution->id }}" {{ ($user->institution_id == $institution->id) ? 'selected' :'' }}>{{ $institution->full_name }}</option>
					@endforeach
				</select>
				@error('institution', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>

		<div class="form-group row m-b-15" id="classes-block">
			<label class="col-form-label col-md-3">{{ __('Классы') }}</label>
			<div class="col-md-9">
				<select multiple="" name="classes[]" class="form-control @error('classes', 'default') is-invalid @enderror selectpicker" data-size="10" data-live-search="true">
					@foreach($institutions as $institution)
						<optgroup label="{{ $institution->short_name }}" institution-id="{{ $institution->id }}">
						@foreach($classes[$institution->id] as $class)
							<option value="{{ $class->id }}" {{ ($user->hasClass($class->id)) ? 'selected':'' }}>{{ $class->name }}</option>
						@endforeach
					</optgroup>
					@endforeach
				</select>
				@error('classes', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>

		<div class="form-group row m-b-15" id="subjects-block">
			<label class="col-form-label col-md-3">{{ __('Предметы') }}</label>
			<div class="col-md-9">
				<select multiple="" name="subjects[]" class="form-control @error('subjects', 'default') is-invalid @enderror selectpicker" data-size="10" data-live-search="true">
					@foreach($subjects as $subject)
						<option value="{{ $subject->id }}" {{ ($user->hasSubject($subject->id)) ? 'selected':'' }}>{{ $subject->name }}</option>
					@endforeach
				</select>
				@error('subjects', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>

		<div class="form-group row m-b-15">
			<label class="col-sm-3 col-form-label">{{ __('Пароль') }}</label>
			<div class="col-sm-9">
				<input name="password" type="text" class="form-control @error('password', 'default') is-invalid @enderror" placeholder="{{ __('Введите пароль') }}">
				@error('password', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>
		<div class="form-group row">
			<div class="col-md-7 offset-md-3">
				<button type="submit" class="btn btn-lg btn-primary m-r-5">{{ __('Сохранить') }}</button>
			</div>
		</div>
	</form>
</div>

resources/views/dashboard/users/edit/email.blade.php
<div class="tab-pane fade @if($settings_tab == 'email-settings') active show @endif" id="email-settings">
	@if($mail_domains->isNotEmpty())
	<form action="{{ route('user.update', $user->id) }}" id="email-settings-form" method="POST">
		@csrf
		{{ method_field('PATCH') }}
		<input type="hidden" name="tab" value="email-settings">

		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Включить почту для аккаунта') }}</label>
			<div class="col-md-9">
				<div class="switcher">
				  	<input type="checkbox" name="active" @if(optional($mail)->active == 1) checked @endif id="email-settings-form-active" value="1">	  	
				  	<label for="email-settings-form-active"></label>
				</div>
			</div>
		</div>
		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Почтовый ящик') }}</label>
			<div class="col-md-9">
				<div class="input-group">
					<input class="form-control @error('username', 'email') is-invalid @enderror @error('domain', 'email') is-invalid @enderror" name="username" value="{{ optional($mail)->username }}" type="text" />
					<select name="domain" class="form-control">
						@foreach($mail_domains as $mail_domain)
						<option value="{{ $mail_domain->id }}" @if($mail_domain->id == optional(optional($mail)->domain)->id) selected @endif>{{ '@'.$mail_domain->domain }}</option>
						@endforeach
					</select>
				</div>
				@error('username', 'email')
                    <span class="invalid-feedback d-block" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
                @error('domain', 'email')
                    <span class="invalid-feedback d-block" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>
		
		<div class="form-group row">
			<div class="col-md-7 offset-md-3">
				<button type="submit" class="btn btn-lg btn-primary m-r-5">{{ __('Сохранить') }}</button>
			</div>
		</div>
	</form>
	@else
	<div class="alert alert-danger fade show mb-0">
		<a href="{{ route('settings.mail') }}" class="alert-link">{{ __('Добавьте почтовый домен') }}</a> 
	</div>
	@endif
</div>

resources/views/dashboard/users/edit/schedule.blade.php
<div class="tab-pane fade @if($settings_tab == 'schedule-settings') active show @endif" id="schedule-settings">
	<form action="{{ route('user.update', $user->id) }}" method="POST">
		@csrf
		{{ method_field('PATCH') }}
		<input type="hidden" name="tab" value="schedule-settings">

		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Разрешить редактировать расписание') }}</label>
			<div class="col-md-9">
				<div class="switcher">
				  	<input type="checkbox" name="enabled" @if($user->getData('edit-schedule-enabled', true) == 1) checked @endif id="schedule-settings-enabled" value="1">	  	
				  	<label for="schedule-settings-enabled"></label>
				</div>
			</div>
		</div>

		<div class="h4">{{ __('Ограничения') }}</div>

		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Редактировать расписания других преподавателей') }}</label>
			<div class="col-md-9">
				<div class="switcher">
				  	<input type="checkbox" name="all_teachers" @if($user->getData('edit-schedule-all-teachers', true) == 1) checked @endif id="schedule-settings-all-teachers" value="1">	  	
				  	<label for="schedule-settings-all-teachers"></label>
				</div>
			</div>
		</div>
		<div class="form-group row m-b-15">
			<label class="col-form-label col-md-3">{{ __('Классы') }}</label>
			<div class="col-md-9">
				<select multiple="" name="classes[]" class="form-control @error('classes', 'default') is-invalid @enderror selectpicker" data-size="10" data-live-search="true">
					@foreach($classes as $class)
						<option value="{{ $class->id }}" {{ (in_array($class->id, (array) $user->getData('edit-schedule-classes', true))) ? 'selected':'' }}>{{ $class->name }}</option>
					@endforeach
				</select>
				@error('classes', 'default')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
			</div>
		</div>

		<div class="form-group row">
			<div class="col-md-7 offset-md-3">
				<button type="submit" class="btn btn-lg btn-primary m-r-5">{{ __('Сохранить') }}</button>
			</div>
		</div>
	</form>
</div>

@push('scripts')
	<!-- <script src="/assets/js/users/edit/schedule.min.js?ver={{ config('app.version') }}"></script>-->
@endpush